version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7  # Choose the desired Python version
    steps:
      - checkout  # Check out your source code
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run pytest
          command: |
            pytest -v --cov=EmployeeManagement
